### ISSUE TITLE
Dibi 3.* and collision of dg/dibi and dibi/dibi

### ISSUE THREAD

**Issue by janfolwarczny** [lightools/transaction-nesting#1]
Hi Jan,

I found yours package and I really like it. Very good work I think. :+1: It completely solved a problem in my app. But I have two problems with this package:
1. It uses Dibi 2.\* (which is without namespaces), but there is Dibi 3. with namespaces.
2. In composer.json is dependency on dibi/dibi, but other packages like Tharos/LeanMapper are dependent on dg/dibi. These are completely same libraries but in different composer packages. Solution for this can be a move of dibi/dibi from require section to suggest section in composer.json. What do you think about it?

Can I create a pull request with these changes or can you change these simple things at your own?

I look forward to hearing from you.
Jan

**Comment by janedbal** [comment]
Hi Jan,
1. There is dibi >= 2.0 in composer.json so it should work with dibi 3.0 (which has BC aliases).
2. What are your dependencies? Because there is a bug in composer (composer/composer#5089) - you can try workaround mentioned there. I tried it right now and with following dependencies and it installs dibi/dibi 3.0.3 without any problems.

``` json
{
    "require": {
        "lightools/transaction-nesting": "^1.0",
        "tharos/leanmapper": "^3.0"
    }
}
```

**Comment by janfolwarczny** [comment]
Hi Jan, 

Thanks for your quick reply. 
1. You are right, there are aliases. I did not know about them.
2. With that workaround works everything fine.
Thanks again and have a nice day!
